// menuData.js

const menuData = [
  {
    category: "Veg Items (Indian)",
    items: [
      { name: "Paneer Curry", half: 120, full: 220, image: "https://www.kitchensanctuary.com/wp-content/uploads/2024/03/Paneer-Curry-square-FS.jpg" },
      { name: "Paneer Do Pyaza", half: 130, full: 230, image: "https://www.whiskaffair.com/wp-content/uploads/2024/07/Paneer-Do-Pyaza-2-3.jpg" },
      { name: "Paneer Masala", half: 130, full: 240, image: "https://homecookingshow.in/wp-content/uploads/2025/05/Dhaba-Paneer-curry-576x1024.webp" },
      { name: "Paneer Butter Masala", half: 130, full: 240, image: "https://myfoodstory.com/wp-content/uploads/2021/07/Paneer-Butter-Masala-3.jpg" },
      { name: "Mix Veg", half: 100, full: 170, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRhFmMGJlfxGvp0zGmsGjUijCWxynckzwvYfQ&s" },
      { name: "Matar Paneer", full: 230, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/03/matar-paneer.jpg" },
      { name: "Paneer Handi", full: 240, image: "https://www.cookclickndevour.com/wp-content/uploads/2017/03/paneer-handi-recipe-c.jpg" },
      { name: "Paneer Kolhapuri", full: 260, image: "https://www.cookclickndevour.com/wp-content/uploads/2017/11/paner-kholapuri-a.jpg" },
      { name: "Paneer Chatpata", full: 260, image: "https://www.chefajaychopra.com/assets/img/recipe/1-1666006926DhabaStyleChatpataPaneerwebp.webp" },
      { name: "Paneer Korma", full: 260, image: "https://images.immediate.co.uk/production/volatile/sites/30/2020/08/paneer-korma-07a67d4.jpg" },
      { name: "Sahi Paneer", full: 260, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/shahi-paneer-recipe.jpg" },
      { name: "Paneer Tawa Masala", full: 260, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/08/tawa-paneer-recipe.jpg" },
      { name: "Paneer Punjabi", full: 270, image: "https://honestcooking.com/wp-content/uploads/2012/09/Paneer-Masala-Recipe.jpg" },
      { name: "Paneer Lababdar", full: 270, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/01/paneer-lababdar.jpg" },
      { name: "Paneer Pasanda", full: 270, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/08/paneer-pasanda-recipe.jpg" },
    { name: "Paneer Tikka Masala", full: 270, image: "https://cdn.prod.website-files.com/65e2ec4e51f6693a3af9151d/660bbc2bf96bfa42f8c93333_f0ef7b68-009e-4c37-bdd5-f67ca31339eb.webp" },
      { name: "Paneer Tikka Butter Masala", full: 270, image: "https://static.toiimg.com/photo/54408184.cms" },
      { name: "Paneer Kofta", full: 260, image: "https://cookwithrenu.com/wp-content/uploads/2023/11/Vegetable-Paneer-Kofta-Curry_Cookwithrenu_Featured-Image-500x500.jpg" },
      { name: "Veg Kofta", full: 220, image: "https://www.theculinarypeace.com/wp-content/uploads/2018/02/temp-110.png" },
      { name: "Malai Kofta", full: 270, image: "https://www.vegrecipesofindia.com/wp-content/uploads/2021/04/malai-kofta-2-500x500.jpg" },
      { name: "Paneer Diwani", full: 270, image: "https://foodoncall.co.in/wp-content/uploads/2017/09/paneer-diwani-handi.jpg" },
      { name: "Paneer Begum", full: 270, image: "https://skydecklounge.in/wp-content/uploads/2022/01/Paneer-Begum-Bahar.jpg" },
      { name: "Paneer Mushroom Masala", full: 260, image: "https://curryandvanilla.com/wp-content/uploads/2024/08/one-pot-paneer-masala-curry-2b.jpg" },
      { name: "Kaju Curry", full: 260, image: "https://cdn2.foodviva.com/static-content/food-images/curry-recipes/kaju-curry/kaju-curry.jpg" },
      { name: "Kaju Korma", full: 270, image: "https://images.news18.com/ibnkhabar/uploads/2021/06/shutterstock_9.jpg" },
      { name: "Hichkii Special Paneer", full: 280, image: "https://c.ndtvimg.com/2020-07/1lm82rsg_paneer-tiffin_625x300_29_July_20.jpg" },
    ],
  },
  {
    category: "Non-Veg Items (Indian)",
    items: [
      { name: "Chicken Curry", half: 140, full: 260, image: "https://www.whiskaffair.com/wp-content/uploads/2021/10/Andhra-Chicken-Curry-2-3.jpg" },
      { name: "Chicken Do Pyaza", half: 150, full: 270, image: "https://sinfullyspicy.com/wp-content/uploads/2023/05/1200-by-1200-images-1.jpg" },
      { name: "Chicken Butter Masala", half: 150, full: 270, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/chicken-butter-masala-recipe.jpg" },
      { name: "Chicken Kadai", half: 150, full: 270, image: "https://www.whiskaffair.com/wp-content/uploads/2020/09/Kadai-Chicken-2-3.jpg" },
      { name: "Chicken Masala", half: 160, full: 290, image: "https://www.whiskaffair.com/wp-content/uploads/2021/01/Chicken-Masala-2-3-1.jpg" },
      { name: "Chicken Handi", full: 280, image: "https://www.indianrecipeinfo.com/wp-content/uploads/2021/12/Chicken-Handi-Recipe.jpg" },
      { name: "Chicken Korma", full: 280, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/08/chicken-korma-recipe.jpg" },
      { name: "Chicken Chatpata", full: 280, image: "https://i.ytimg.com/vi/ny8oEOzOaas/maxresdefault.jpg" },
      { name: "Chicken Kolhapuri", full: 280, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/09/kolhapuri-chicken-recipe.jpg" },
      { name: "Chicken Bharta", full: 280, image: "https://myfoodstory.com/wp-content/uploads/2024/11/Chicken-Bharta-3.jpg" },
      { name: "Chicken Lababdar", full: 280, image: "https://india.amritsr.com/wp-content/uploads/2022/09/Tandoori-Chicken-Lababdar.jpg" },
      { name: "Chicken Punjabi", full: 280, image: "https://www.deliciousmagazine.co.uk/wp-content/uploads/2021/01/Chicken_Curry-768.jpg" },
      { name: "Chicken Tikka Masala", full: 290, image: "https://www.recipetineats.com/tachyon/2018/04/Chicken-Tikka-Masala_0-SQ.jpg" },
      { name: "Chicken Tikka Butter Masala", full: 290, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/chicken-tikka-masala-500x500.jpg" },
      { name: "Chicken Dehati", half: 250, image: "https://myblacktree.com/cdn/shop/files/Tomato-Chicken-Curry-2-3-removebg-preview.png" },
      { name: "Chicken Murg Massalam", full: 510, image: "https://images.archanaskitchen.com/images/recipes/indian/main-course/indian-non-veg-recipes/chicken-recipes/Murgh_Masala_86d1eb38ed.jpg" },
      { name: "Hichkii Special Chicken", full: 310, image: "https://i0.wp.com/www.lizzielikes.com/wp-content/uploads/2020/05/special-chicken-10.jpg" },
      { name: "Egg Curry", full: 80, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/04/egg-curry.webp" },
      { name: "Egg Do Pyaza", full: 90, image: "https://jeyporedukaan.in/wp-content/uploads/2022/09/images-17.jpeg" },
      { name: "Egg Masala / Kadai", full: 100, image: "https://www.sharmispassions.com/wp-content/uploads/2013/02/EggMasala4.jpg" },
      { name: "Omelette Curry", full: 110, image: "https://vismaifood.com/storage/app/uploads/public/e50/b28/4cb/thumb__700_0_0_0_auto.jpg" },
    ],
  },
  {
    category: "Mushroom Items",
    items: [
      { name: "Mushroom Curry", full: 220, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/12/mushroom-curry-recipe-indian.jpg" },
      { name: "Mushroom Do Pyaza", full: 230, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS4rNInv_TaxejPY-3ZA9nNsucnmbAObgA-Qw&s" },
      { name: "Mushroom Masala", full: 240, image: "https://www.vegrecipesofindia.com/wp-content/uploads/2025/04/mushroom-masala-curry-recipe.jpg" },
      { name: "Mushroom Butter Masala", full: 240, image: "https://www.cookwithkushi.com/wp-content/uploads/2020/03/IMG_3557_11-1024x650-1.jpg" },
      { name: "Mushroom Kadai", full: 240, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/kadai-mushroom-recipe.jpg" },
    ],
  },
  {
    category: "Chinese Items (Veg)",
    items: [
      { name: "Veg Manchurian (4pc/8pc)", half: 75, full: 140, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgHJIfFAjPcUc-ZGPqYHZ46Zy9Znhig-XBlA&s" },
      { name: "Veg Chilli (4pc/8pc)", half: 75, full: 140, image: "https://images.immediate.co.uk/production/volatile/sites/30/2024/12/Next-level-veg-chilli-8fab1b0.jpg?resize=900%2C471" },
      { name: "Paneer Chilli", half: 110, full: 210, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/chilli-paneer-recipe.jpg" },
      { name: "Paneer Manchurian (8pc)", full: 220, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/08/paneer-manchurian-recipe.jpg" },
      { name: "Soyabeen Chilli", full: 170, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSfADVHqVWhdsYOFoald3AFgnNfzjQPITG-Cw&s" },
      { name: "Baby Corn Chilli", full: 230, image: "https://myfoodstory.com/wp-content/uploads/2022/04/Crispy-Babycorn-Chilli-4-1.jpg" },
      { name: "Mushroom Chilli", full: 210, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2012/12/chilli-mushroom-stir-fry-500x375.jpg" },
    ],
  },
  {
    category: "Chinese Items (Non-Veg)",
    items: [
      { name: "Chicken Chilli (Bone) (6pc/12pc)", half: 120, full: 230, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2018/07/chilli-chicken-recipe-500x500.jpg" },
      { name: "Chicken Chilli Boneless (6pc/12pc)", half: 120, full: 230, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCCBNyL4klKWbljbR_PDeJkAh-1n5OP2B6Xw&s" },
      { name: "Chicken Manchurian (8pc)", full: 240, image: "https://happietrio.com/wp-content/uploads/2016/06/ChickenManchurian.jpg" },
      { name: "Chicken Lolipop (6pc/12pc)", half: 120, full: 220, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/chicken-lollipop.jpg" },
      { name: "Chicken Garlic (8pc)", full: 210, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQSBC61VhTz4C5p2z362MThEFQ_VYMlCagMwA&s" },
    ],
  },
  {
    category: "Roti & Paratha",
    items: [
      { name: "Tandoori Roti", full: 12, image: "https://www.cookwithmanali.com/wp-content/uploads/2021/07/Tandoori-Roti-500x375.jpg" },
      { name: "Tandoori Butter Roti", full: 15, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/09/tandoori-roti-recipe.jpg" },
      { name: "Plain Naan", full: 25, image: "https://www.vegrecipesofindia.com/wp-content/uploads/2025/05/naan-3-500x500.jpg" },
      { name: "Butter Naan", full: 30, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTu0yBjOvU4BwUI5r6tJhYU5CQlAYOrqHphIg&s" },
      { name: "Lachha Paratha", full: 30, image: "https://myfoodstory.com/wp-content/uploads/2022/08/Homemade-Lachha-Paratha-2.jpg" },
      { name: "Plain Kulcha", full: 30, image: "https://www.vegrecipesofindia.com/wp-content/uploads/2018/10/kulcha-recipe-1.jpg" },
      { name: "Garlic Naan", full: 50, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS80TGX1kM7df9XDBvybUmJWCDgYqK6OrroOA&s" },
      { name: "Veg Stuff Naan", full: 50, image: "https://fullofplants.com/wp-content/uploads/2019/05/potato-stuffed-naan-vegan-thumb-2.jpg" },
      { name: "Paneer Stuff Naan", full: 70, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRNXE3uFe5TKMEKtLTlCqigsI05r_QhLuGqjQ&s" },
      { name: "Veg Masala Kulcha", full: 50, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSHQDtL2zxJT0OegiZIuvIhSclMzK5bC0VVsQ&s" },
      { name: "Paneer Kulcha", full: 70, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsy019jaHSaq-wGol-Df15hg6JMubVzD3yfQ&s" },
      { name: "Aaloo Paratha", full: 40, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmgf8nAQeSf7lOkSgVq2rtcquXiXCdHMO3hA&s" },
      { name: "Paneer Paratha", full: 70, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQxicjY3IPYzmBJBIVHBPmZrXYx0vMGr02s4A&s" },
      { name: "Egg Paratha", full: 50, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2024/06/egg-paratha-anda-paratha.jpg" },
    ],
  },
  {
    category: "Roll Items",
    items: [
      { name: "Veg Roll", full: 45, image: "https://spicecravings.com/wp-content/uploads/2020/12/Paneer-kathi-Roll-Featured-1.jpg" },
      { name: "Paneer Roll", full: 60, image: "https://spicecravings.com/wp-content/uploads/2020/12/Paneer-kathi-Roll-Featured-1.jpg" },
      { name: "Single Egg Roll", full: 50, image: "https://fuddins.com/wp-content/uploads/2023/03/60f2ea67b471327a1d82959b_chicken-roll_1500-x-1200.jpg" },
      { name: "Double Egg Roll", full: 60, image: "https://gully2gully.in/wp-content/uploads/2021/12/egg-roll.jpg" },
      { name: "Chicken Roll", full: 65, image: "https://www.licious.in/blog/wp-content/uploads/2022/12/Shutterstock_2132499279-600x600.jpg" },
      { name: "Egg Chicken Roll", full: 70, image: "https://foodiesterminal.com/wp-content/uploads/2018/10/Egg-Chicken-roll-recipe-Kolkata-style-854x1024.jpg" },
      { name: "Double Egg Chicken Roll", full: 80, image: "https://i.ytimg.com/vi/GoizL4OOy8w/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLABdhaaBKuLipQyhY43ctNpc3L1cA" },
      { name: "Double Egg Double Chicken Roll", full: 95, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXWvjkghcWOpF1OW9_IUItIc8Av3jJZwJzlg&s" },
      { name: "Special Chicken Roll", full: 110, image: "https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEgnx7i5vsjF_3YFyqk5VDKiRIPKztVnTp08qCQ5_QBF6tyZSny6NJnKTnsgSHJIpwgyAxKpV9iXAsL8aJv_lKkQg6HzzNVDSwNrf5xHbUUGScmq8V1TbHa2iR8KNQdeTT6iwaaTlWkbQJE/s2000-rw/IMG_20210404_223034_compress19.jpg" },
    ],
  },
  {
    category: "Noodles (Chowmin)",
    items: [
      { name: "Veg Chowmin", half: 45, full: 80, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5_6Sv8JMgorHh60hB4eEuhShrNewNPbrUog&s" },
      { name: "Egg Chowmin", half: 50, full: 90, image: "https://i.ytimg.com/vi/_i10tOFXTbw/sddefault.jpg" },
      { name: "Double Egg Chowmin", half: 60, full: 110, image: "https://i.ytimg.com/vi/7wIMaLJvL0U/maxresdefault.jpg" },
      { name: "Paneer Chowmin", half: 60, full: 110, image: "https://sinfullyspicy.com/wp-content/uploads/2022/02/1.jpg" },
      { name: "Chicken Chowmin", half: 70, full: 130, image: "https://breakthespicerecipes.com/wp-content/uploads/2023/04/Chicken-chow-mein-1.jpg" },
      { name: "Chicken Mix Chowmin", half: 70, full: 150, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuGSVGPSxueFiLom5S8urzfy1a4_rwVh0RgA&s" },
      { name: "Veg Mix Chowmin", full: 140, image: "https://www.cookwithmanali.com/wp-content/uploads/2024/01/Veg-Chowmein.jpg" },
    ],
  },
  {
    category: "Rice Items",
    items: [
      { name: "Plain / Steam Rice", half: 40, full: 70, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNWWVoEkAyshfHzP1xKp2SfjOyG9WtUbnkqw&s" },
      { name: "Jeera Rice", half: 50, full: 80, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/12/jeera-rice-recipe.webp" },
      { name: "Veg Fried Rice", half: 60, full: 100, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/12/fried-rice-500x500.jpg" },
      { name: "Paneer Fried Rice", half: 65, full: 120, image: "https://www.indianveggiedelight.com/wp-content/uploads/2023/09/paneer-fried-rice-featured.jpg" },
      { name: "Chicken Fried Rice", half: 75, full: 130, image: "https://www.sharmispassions.com/wp-content/uploads/2018/03/chicken-fried-rice7-500x500.jpg" },
      { name: "Egg Fried Rice", half: 65, full: 120, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/07/egg-fried-rice-recipe.jpg" },
      { name: "Plain Pulao", full: 120, image: "https://thewannabecook.com/wp-content/uploads/2022/07/Plain_Pulao_recipe-e1662690365484.jpg" },
      { name: "Veg Pulao", full: 140, image: "https://www.cubesnjuliennes.com/wp-content/uploads/2019/11/Veg-Pulao-2.jpg" },
      { name: "Paneer Pulao", full: 150, image: "https://cdn.indiaphile.info/wp-content/uploads/2023/02/stp-paneer-pulao-0023.jpg?width=1200&crop_gravity=center&aspect_ratio=2:3&q=75" },
      { name: "Chicken Pulao", full: 180, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/05/chicken-pulao-recipe-500x500.jpg" },
    ],
  },
  {
    category: "Biryani",
    items: [
      { name: "Chicken Biryani", half: 100, full: 200, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/chicken-biryani-recipe.jpg" },
      { name: "Veg Biryani", half: 90, full: 160, image: "https://madhurasrecipe.com/wp-content/uploads/2023/03/Veg-Biryani-2.jpg" },
      { name: "Paneer Biryani", half: 90, full: 170, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/02/paneer-biryani-recipe.jpg" },
      { name: "Egg Biryani", half: 90, full: 160, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/02/instant-pot-egg-biryani-500x500.jpg" },
      { name: "Chicken Hyderabadi Biryani", full: 230, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/hyderabadi-biryani-recipe-chicken.jpg" },
      { name: "Paneer Hyderabadi Biryani", full: 220, image: "https://images.archanaskitchen.com/images/recipes/indian/main-course/indian-rice-recipes/biryani-recipes/Paneer_Biryani_Recipe_1_238b9b14cb.jpg" },
      { name: "Veg Hyderabadi Biryani", full: 210, image: "https://kannanskitchen.com/wp-content/uploads/2021/04/DSC_1079_1.jpg" },
    ],
  },
  {
    category: "Salad & Raita",
    items: [
      { name: "Green Salad", full: 60, image: "https://www.kitchensanctuary.com/wp-content/uploads/2021/06/Simple-Green-Salad-with-Vinaigrette-Square-FS-3241-500x500.jpg" },
      { name: "Onion Salad", full: 50, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/07/onion-salad-recipe.jpg" },
      { name: "Veg Raita", full: 40, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/raita-recipes-500x375.jpg" },
    ],
  },
  {
    category: "Papad",
    items: [
      { name: "Papad Dry", full: 20, image: "https://sindhidryfruits.live/cdn/shop/products/BikaneriPapad.jpg?v=1741509548" },
      { name: "Papad Fry", full: 25, image: "https://cdn.jhattse.com/resize?width=640&url=https://jhattse.com/api/v1/file/?key=images/product/114599/108419/MI896EAA-Fry-papad-1.jpg&quality=75&type=webp" },
      { name: "Papad Masala", full: 70, image: "https://madhurasrecipe.com/wp-content/uploads/2020/10/Masala-Papad-Marathi-Recipe-feature.jpg" },
    ],
  },
  {
    category: "Soup",
    items: [
      { name: "Veg Soup", full: 60, image: "https://www.inspiredtaste.net/wp-content/uploads/2018/10/Homemade-Vegetable-Soup-Recipe-2-1200.jpg" },
      { name: "Veg Hot & Sour", full: 70, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRWLteqwORRI83yeM-ti5b_fRivux7XQW-C8w&s" },
      { name: "Veg Man Chow", full: 80, image: "https://www.secondrecipe.com/wp-content/uploads/2020/06/veg-manchow-soup.jpg" },
      { name: "Tomato Soup", full: 80, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/11/tomato-soup-recipe.jpg" },
      { name: "Chicken Soup", full: 90, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZGzx_uDXiXBCfX-iCG1p45HQeP2_SN4AKfw&s" },
      { name: "Chicken Hot & Sour", full: 100, image: "https://butteroverbae.com/wp-content/uploads/2020/11/hot-and-sour-soup-2.jpg" },
      { name: "Chicken Manchow", full: 110, image: "https://sinfullyspicy.com/wp-content/uploads/2023/12/1200-by-1200-images-1.jpg"},
      { name: "Chicken Hot Mongolian Soup", full: 130, image: "https://thedefineddish.com/wp-content/uploads/2023/07/230707_mongolian-chicken-08.jpg" },
    ],
  },
  {
    category: "Starters (Veg)",
    items: [
      { name: "Paneer Lemon Chilly", full: 230, image: "https://images.archanaskitchen.com/images/recipes/world-recipes/continental-party-appetizer-starter-recipes/Spicy_Lemon_Chilli_Paneer_Tart_with_Curry_leaves_Recipe_ddba2e5ce1.jpg" },
      { name: "Veg Pakora", full: 130, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/vegetable-pakora-recipe.jpg" },
      { name: "Paneer Pakora", full: 170, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2016/06/paneer-pakoda.jpg" },
      { name: "Veg Crispy", full: 210, image: "https://madhurasrecipe.com/wp-content/uploads/2020/10/Veg-Crispy-feature-585x426.jpg" },
      { name: "Veg Mangolian", full: 230, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQESGptH9rZ60JL-64ff34t-ZFb7yiZUZ391Q&s" },
      { name: "Paneer Mangolian (8pc)", full: 230, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTpA1QlccF7mpcs8WhTQOJBwFmNRXNf5wF86w&s" },
      { name: "Baby Corn Cryspy", full: 230, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT8Y6_v2leu4tPOhK20yHddnDNFO9zWSQPqQg&s" },
      { name: "Paneer Lolipop", full: 220, image: "https://img-cdn.publive.online/fit-in/1200x675/sanjeev-kapoor/media/post_banners/4f267e0b99af6ef8aca7184a1b99c57dc5da39299780c9d06a439d9702d903e2.jpg" },
      { name: "Paneer Singapore", full: 250, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/08/paneer-amritsari.webp" },
      { name: "Paneer 65", full: 250, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/06/paneer-65-recipe.jpg" },
    ],
  },
  {
    category: "Starters (Non-Veg)",
    items: [
    { name: "Chicken Pakora (Bone)", full: 240, image: "https://i.ytimg.com/vi/DjvgU6v-RxM/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBMIP-Ycaw9PLofpxIgFus5Ahac_A" },
    { name: "Chicken Pakora (B/L)", full: 240, image: "https://i.ytimg.com/vi/7ceAGKonFTE/maxresdefault.jpg" },
    { name: "Chicken Lolipop", full: 220, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/12/chicken-lollipop.jpg" },
    { name: "Chicken Lemon Chilli", full: 240, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPDJ4gaqy0xJpYKPF1OkFfdNGDyDR0sk7CRQ&s" },
    { name: "Chicken Kalimirch Dry", full: 250, image: "https://www.licious.in/blog/wp-content/uploads/2022/09/Shutterstock_1890549250-750x750.jpg" },
    { name: "Chicken Mongolian Dry", full: 250, image: "https://www.dinneratthezoo.com/wp-content/uploads/2018/08/mongolian-chicken-4.jpg" },
    { name: "Chicken Mumbaiya Chilly", full: 270, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2023/12/chilli-chicken-recipe.jpg" },
    { name: "Chicken Singapore", full: 270, image: "https://www.nzherald.co.nz/resizer/v2/TH3GWDBL2BEBTKNZARJVQL3RGI.jpg?auth=295ab3c5816ad36568e79706e0fe050d10a6b84567ac3b9724dc54a28913298b&width=576&height=613&quality=70&smart=true" },
    { name: "Chicken Spring", full: 250, image: "https://i.ytimg.com/vi/4vKiaay10EQ/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAX3Z070tzUnBhofnXzYSzCejXDoQ" },
    { name: "Chicken 65", full: 270, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/03/chicken-65-restaurant-style.jpg" },
],
  },
  {
    category: "Dal",
    items: [
      { name: "Plain Dal", full: 60, image: "https://www.whiskaffair.com/wp-content/uploads/2020/04/North-Indian-Homestyle-Toor-Dal-2-3.jpg" },
      { name: "Dal Fried", full: 70, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/02/dal-fry.jpg" },
      { name: "Dal Tarka", full: 70, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2021/04/dal-tadka.jpg" },
      { name: "Dal Makhana", full: 90, image: "https://www.indianhealthyrecipes.com/wp-content/uploads/2022/02/dal-makhani-recipe.webp" },
    ],
  },
  {
    category: "Tandoori Items",
    items: [
      { name: "Paneer Tikka", full: 240, image: "https://www.cookwithmanali.com/wp-content/uploads/2015/07/Restaurant-Style-Recipe-Paneer-Tikka-500x500.jpg" },
      { name: "Paneer Seek Kabab", full: 250, image: "https://i.ytimg.com/vi/3ZcjzNn2W44/maxresdefault.jpg" },
      { name: "Chicken Tikka", full: 260, image: "https://www.eitanbernath.com/wp-content/uploads/2020/10/Chicken-Tikka-LOW-RES-1-819x1024.jpg" },
      { name: "Chicken Seek Kabab", full: 280, image: "https://www.eatdrinkpure.com/wp-content/uploads/2025/02/Chicken-Seekh-Kebab.jpg" },
      { name: "Chicken Tandoori", full: 420, image: "https://www.allrecipes.com/thmb/ayYKam8g3aGUfLZdVvhnwrRxXuw=/0x512/filters:no_upscale():max_bytes(150000):strip_icc()/50347-indian-tandoori-chicken-DDMFS-4x3-3035-205e98c80b2f4275b5bd010c396d9149.jpg" },
    ],
  },
];

export default menuData;